os: Visual Studio 2015

platform:
  - Win32

configuration:
  - Debug
  - Release

install:
  - cd c:\projects\metashell\3rd\templight
  - appveyor DownloadFile https://github.com/metashell/templight_binary/releases/download/templight_185020_v2/templight_windows.zip
  - 7z -y x templight_windows.zip
  - choco install nsis -version 2.50.0.20160103

before_build:
  - cd c:\projects\metashell
  - md bin
  - cd bin
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 12
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 12 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" ..

build_script:
  - cd c:\projects\metashell
  - set NO_TEMPLIGHT=1
  - build.bat
